using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MolinaEventProgramming
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            this.MouseClick += new MouseEventHandler(this.Form1_MyEvent);
            this.KeyPress += new KeyPressEventHandler(Form1_MyKeyPress);

        }

        public void Form1_MyKeyPress(object sender, KeyPressEventArgs e)
        {
            MessageBox.Show("Key Pressed: " + e.KeyChar);
        }

        public void Form1_MyEvent(object sender, EventArgs e)
        {
            MessageBox.Show("In Form1_MyEvent: Mouse Clicked!");
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            MessageBox.Show("Bye!!!");
        }

        private void Form1_MouseClick(object sender, MouseEventArgs e)
        {
            MessageBox.Show("Autogenerated method: Mouse Clicked!");
        }

        private void Form1_KeyDown(object sender, KeyEventArgs e)
        {
            String keyPressed = "";

            keyPressed += (e.Alt ? "Alt" : "");
            keyPressed += (e.Shift ? "Shift" : "");
            keyPressed += (e.Control ? "Control" : "");

            MessageBox.Show("Key Pressed = " + keyPressed);
        }
    }
}
